const INITIAL_CLICK_COUNTER = 1;
const ZINDEX_FOR_CLICK = '7';
const BASE_ZINDEX = '2';
const NEGATIVE_BURGER_WRAPPER_WIDTH = '-320px';
const HEADERS_ARRAY_INDEX = 0;
const EVERY_THIRD_CATEGORY_OBJECT = 2;
const CATEGORIES_ARRAY_LAST_INDEX = 7;
const CATEGORIES_ARRAY_LENGTH = 8;
const CARDS_IN_CATEGORY = 8;

export {
  INITIAL_CLICK_COUNTER,
  ZINDEX_FOR_CLICK,
  NEGATIVE_BURGER_WRAPPER_WIDTH,
  HEADERS_ARRAY_INDEX,
  EVERY_THIRD_CATEGORY_OBJECT,
  BASE_ZINDEX,
  CATEGORIES_ARRAY_LAST_INDEX,
  CATEGORIES_ARRAY_LENGTH,
  CARDS_IN_CATEGORY,
};
